- hosts: "*"
  become: yes
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

    - name: reboot
      reboot:
        reboot_timeout: 5000