- hosts: "*"
  become: yes
  tasks:
    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists