- hosts: "all"
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: reboot
      reboot:
        reboot_timeout: 5000

    - name: add droid to sudo group
      shell: 'usermod -aG sudo droid'