- hosts: "single"
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: reboot
      reboot:
        reboot_timeout: 5000

    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

    - name: reboot
      reboot:
        reboot_timeout: 5000